"""
apply_materials.py — Auto-generated by render_to_pbr.py
Run: blender --background input.blend --python apply_materials.py -- output.blend
"""
import bpy, os

TEXTURE_DIRS = {
  "wall_white": null
}
ROOM_MATERIALS = {
  "cocina": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      208.125,
      0.10648147761821747,
      0.7254902124404907
    ]
  },
  "sala": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      206.6666717529297,
      0.0896226316690445,
      0.8352941274642944
    ]
  },
  "room_2": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      210.0,
      0.09649122506380081,
      0.8901960849761963
    ]
  },
  "room_3": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      204.0,
      0.039215683937072754,
      0.9843137264251709
    ]
  },
  "balcon": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      210.0,
      0.11059907078742981,
      0.8509804010391235
    ]
  },
  "master": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      208.69566345214844,
      0.08260869234800339,
      0.9019607901573181
    ]
  },
  "hab": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      207.27272033691406,
      0.07725321501493454,
      0.8470588326454163
    ]
  },
  "comedor": {
    "surface": "wall_white",
    "ph_id": null,
    "hsv": [
      200.00001525878906,
      0.045267485082149506,
      0.9137254953384399
    ]
  }
}

def load_texture(path):
    if path and os.path.exists(path):
        if path in bpy.data.images:
            return bpy.data.images[path]
        return bpy.data.images.load(path)
    return None

def make_pbr_mat(name, tex_dir, base_color=(0.9, 0.88, 0.85, 1.0), roughness=0.85):
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.location = (0, 0)
    out.location = (300, 0)
    links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])

    if tex_dir and os.path.isdir(tex_dir):
        diffuse_path = os.path.join(tex_dir, "diffuse.jpg")
        rough_path   = os.path.join(tex_dir, "roughness.jpg")
        normal_path  = os.path.join(tex_dir, "normal.jpg")
        ao_path      = os.path.join(tex_dir, "ao.jpg")

        coord = nodes.new("ShaderNodeTexCoord"); coord.location = (-800, 0)
        mapping = nodes.new("ShaderNodeMapping"); mapping.location = (-600, 0)
        links.new(coord.outputs["UV"], mapping.inputs["Vector"])

        if os.path.exists(diffuse_path):
            diff_tex = nodes.new("ShaderNodeTexImage")
            diff_tex.location = (-300, 200)
            diff_tex.image = load_texture(diffuse_path)
            diff_tex.image.colorspace_settings.name = "sRGB"
            links.new(mapping.outputs["Vector"], diff_tex.inputs["Vector"])
            links.new(diff_tex.outputs["Color"], bsdf.inputs["Base Color"])

        if os.path.exists(rough_path):
            rough_tex = nodes.new("ShaderNodeTexImage")
            rough_tex.location = (-300, -100)
            rough_tex.image = load_texture(rough_path)
            rough_tex.image.colorspace_settings.name = "Non-Color"
            links.new(mapping.outputs["Vector"], rough_tex.inputs["Vector"])
            links.new(rough_tex.outputs["Color"], bsdf.inputs["Roughness"])

        if os.path.exists(normal_path):
            norm_tex = nodes.new("ShaderNodeTexImage")
            norm_tex.location = (-300, -350)
            norm_tex.image = load_texture(normal_path)
            norm_tex.image.colorspace_settings.name = "Non-Color"
            norm_map = nodes.new("ShaderNodeNormalMap")
            norm_map.location = (-50, -350)
            links.new(mapping.outputs["Vector"], norm_tex.inputs["Vector"])
            links.new(norm_tex.outputs["Color"], norm_map.inputs["Color"])
            links.new(norm_map.outputs["Normal"], bsdf.inputs["Normal"])
    else:
        bsdf.inputs["Base Color"].default_value = base_color
        bsdf.inputs["Roughness"].default_value = roughness

    return mat

# Apply materials to objects by name matching
for obj in bpy.data.objects:
    if obj.type != "MESH":
        continue
    name_lower = obj.name.lower()
    mat = None

    if "floor" in name_lower:
        room_key = next((k for k in ROOM_MATERIALS if k in name_lower), None)
        surface = ROOM_MATERIALS.get(room_key, {}).get("surface", "wood_floor")
        tex_dir = TEXTURE_DIRS.get(surface)
        mat = make_pbr_mat(f"mat_floor_{room_key}", tex_dir, (0.52, 0.38, 0.22, 1), 0.6)
    elif "wall" in name_lower or "base" in name_lower:
        mat = make_pbr_mat("mat_wall", None, (0.94, 0.93, 0.91, 1), 0.88)
    elif "ceiling" in name_lower or "ceil" in name_lower:
        mat = make_pbr_mat("mat_ceiling", None, (0.98, 0.98, 0.97, 1), 0.96)
    elif "glass" in name_lower:
        mat = make_pbr_mat("mat_glass", None, (0.8, 0.9, 1.0, 1), 0.05)
        mat.blend_method = "BLEND"
        mat.node_tree.nodes["Principled BSDF"].inputs["Alpha"].default_value = 0.15
    elif "door" in name_lower:
        mat = make_pbr_mat("mat_door", None, (0.45, 0.30, 0.18, 1), 0.55)

    if mat and obj.material_slots:
        obj.material_slots[0].material = mat
    elif mat:
        obj.data.materials.append(mat)

print("Materials applied successfully")
