"""
apply_materials.py — Auto-generated by render_to_pbr.py
Run: blender --background input.blend --python apply_materials.py -- output.blend
"""
import bpy, os

TEXTURE_DIRS = {
  "wall_white": null,
  "wood_floor": "pbr_textures/wood_floor_deck"
}
ROOM_MATERIALS = {
  "room_0": {
    "floor_surface": "wall_white",
    "floor_ph_id": null,
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      219.4279022216797,
      0.06176307052373886,
      0.6274510025978088
    ]
  },
  "room_1": {
    "floor_surface": "wood_floor",
    "floor_ph_id": "wood_floor_deck",
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      28.064516067504883,
      0.3893181383609772,
      0.4941176474094391
    ]
  },
  "room_2": {
    "floor_surface": "wall_white",
    "floor_ph_id": null,
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      120.0,
      0.02578982152044773,
      0.6980392336845398
    ]
  },
  "room_3": {
    "floor_surface": "wall_white",
    "floor_ph_id": null,
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      225.79830932617188,
      0.09596779942512512,
      0.7529411911964417
    ]
  },
  "room_4": {
    "floor_surface": "wall_white",
    "floor_ph_id": null,
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      217.5,
      0.05420202761888504,
      0.6274510025978088
    ]
  },
  "room_5": {
    "floor_surface": "wood_floor",
    "floor_ph_id": "wood_floor_deck",
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      25.958049774169922,
      0.5232716798782349,
      0.4745098054409027
    ]
  },
  "room_6": {
    "floor_surface": "wall_white",
    "floor_ph_id": null,
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      231.42857360839844,
      0.07547913491725922,
      0.686274528503418
    ]
  },
  "room_7": {
    "floor_surface": "wall_white",
    "floor_ph_id": null,
    "wall_surface": "wall_white",
    "wall_ph_id": null,
    "hsv": [
      22.85713768005371,
      0.09037845581769943,
      0.5960784554481506
    ]
  }
}

def load_texture(path):
    if path and os.path.exists(path):
        if path in bpy.data.images:
            return bpy.data.images[path]
        return bpy.data.images.load(path)
    return None

def make_pbr_mat(name, tex_dir, base_color=(0.9, 0.88, 0.85, 1.0), roughness=0.85):
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.location = (0, 0)
    out.location = (300, 0)
    links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])

    if tex_dir and os.path.isdir(tex_dir):
        diffuse_path = os.path.join(tex_dir, "diffuse.jpg")
        rough_path   = os.path.join(tex_dir, "roughness.jpg")
        normal_path  = os.path.join(tex_dir, "normal.jpg")
        ao_path      = os.path.join(tex_dir, "ao.jpg")

        coord = nodes.new("ShaderNodeTexCoord"); coord.location = (-800, 0)
        mapping = nodes.new("ShaderNodeMapping"); mapping.location = (-600, 0)
        links.new(coord.outputs["UV"], mapping.inputs["Vector"])

        if os.path.exists(diffuse_path):
            diff_tex = nodes.new("ShaderNodeTexImage")
            diff_tex.location = (-300, 200)
            diff_tex.image = load_texture(diffuse_path)
            diff_tex.image.colorspace_settings.name = "sRGB"
            links.new(mapping.outputs["Vector"], diff_tex.inputs["Vector"])
            links.new(diff_tex.outputs["Color"], bsdf.inputs["Base Color"])

        if os.path.exists(rough_path):
            rough_tex = nodes.new("ShaderNodeTexImage")
            rough_tex.location = (-300, -100)
            rough_tex.image = load_texture(rough_path)
            rough_tex.image.colorspace_settings.name = "Non-Color"
            links.new(mapping.outputs["Vector"], rough_tex.inputs["Vector"])
            links.new(rough_tex.outputs["Color"], bsdf.inputs["Roughness"])

        if os.path.exists(normal_path):
            norm_tex = nodes.new("ShaderNodeTexImage")
            norm_tex.location = (-300, -350)
            norm_tex.image = load_texture(normal_path)
            norm_tex.image.colorspace_settings.name = "Non-Color"
            norm_map = nodes.new("ShaderNodeNormalMap")
            norm_map.location = (-50, -350)
            links.new(mapping.outputs["Vector"], norm_tex.inputs["Vector"])
            links.new(norm_tex.outputs["Color"], norm_map.inputs["Color"])
            links.new(norm_map.outputs["Normal"], bsdf.inputs["Normal"])
    else:
        bsdf.inputs["Base Color"].default_value = base_color
        bsdf.inputs["Roughness"].default_value = roughness

    return mat

# Apply materials to objects by name matching
for obj in bpy.data.objects:
    if obj.type != "MESH":
        continue
    name_lower = obj.name.lower()
    mat = None

    if "floor" in name_lower:
        room_key = next((k for k in ROOM_MATERIALS if k in name_lower), None)
        rm = ROOM_MATERIALS.get(room_key, {})
        surface = rm.get("floor_surface", "wood_floor")
        tex_dir = TEXTURE_DIRS.get(surface)
        mat = make_pbr_mat(f"mat_floor_{room_key or 'default'}", tex_dir, (0.52, 0.38, 0.22, 1), 0.6)
    elif "wall" in name_lower or "base" in name_lower:
        room_key = next((k for k in ROOM_MATERIALS if k in name_lower), None)
        rm = ROOM_MATERIALS.get(room_key, {})
        w_surface = rm.get("wall_surface", "wall_white")
        w_tex = TEXTURE_DIRS.get(w_surface)
        mat = make_pbr_mat(f"mat_wall_{room_key or 'default'}", w_tex, (0.94, 0.93, 0.91, 1), 0.88)
    elif "ceiling" in name_lower or "ceil" in name_lower:
        mat = make_pbr_mat("mat_ceiling", None, (0.98, 0.98, 0.97, 1), 0.96)
    elif "glass" in name_lower:
        mat = make_pbr_mat("mat_glass", None, (0.8, 0.9, 1.0, 1), 0.05)
        mat.blend_method = "BLEND"
        mat.node_tree.nodes["Principled BSDF"].inputs["Alpha"].default_value = 0.15
    elif "door" in name_lower:
        mat = make_pbr_mat("mat_door", None, (0.45, 0.30, 0.18, 1), 0.55)

    if mat and obj.material_slots:
        obj.material_slots[0].material = mat
    elif mat:
        obj.data.materials.append(mat)

print("Materials applied successfully")
